dist: xenial
language: java
jdk: openjdk11

env:
  global:
    - MAVEN_OPTS="-Xmx512m"
  matrix:
    - ECLIPSE_RELEASE="-Declipse-release=2021-09"
    - ECLIPSE_RELEASE="-Declipse-release=2021-12"
    - ECLIPSE_RELEASE="-Declipse-release=2022-03"
    - ECLIPSE_RELEASE="-Declipse-release=2022-06"

services:
  - xvfb

cache:
  directories:
    - $HOME/.m2

install: true

script: mvn clean verify -f ch.acanda.eclipse.pmd/pom.xml -B $ECLIPSE_RELEASE
