dist: xenial
language: java
jdk: openjdk8

env:
  global:
    - MAVEN_OPTS="-Xmx512m"
  matrix:
    - ECLIPSE_RELEASE="-Declipse-release=2019-06"
    - ECLIPSE_RELEASE="-Declipse-release=2019-09"
    - ECLIPSE_RELEASE="-Declipse-release=2019-12"
    - ECLIPSE_RELEASE="-Declipse-release=2020-03"

services:
  - xvfb

cache:
  directories:
    - $HOME/.m2

install: true

script: mvn clean verify -f ch.acanda.eclipse.pmd/pom.xml -B $ECLIPSE_RELEASE
