name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        release: [2022-09, 2022-12, 2023-03, 2023-06]
    steps:
      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.9.0
        with:
          checkout-fetch-depth: 0
          java-version: 17
          maven-version: 3.9.3
      - name: Build ${{ matrix.release }}
        run: DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' mvn -f eclipse-pmd/pom.xml -B verify -Declipse-release=${{ matrix.release }}
