name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        release: [2023-09, 2023-12, 2024-03, 2024-06]
    steps:
      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.13.0
        with:
          checkout-fetch-depth: 0
          java-version: 17
          maven-version: 3.9.6
      - name: Build ${{ matrix.release }}
        run: DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' mvn -f eclipse-pmd/pom.xml -B verify -Declipse-release=${{ matrix.release }}
