name: Sonar
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Sonar
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          checkout-fetch-depth: 0
          java-version: 21
          maven-version: 3.9.9
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-sonar-
      - name: Build and run Sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' mvn -f eclipse-pmd/pom.xml -B -Pjacoco verify org.sonarsource.scanner.maven:sonar-maven-plugin:5.1.0.4751:sonar
      - name: Summary
        run: |
          echo "# Sonar" >> $GITHUB_STEP_SUMMARY
          echo "You can find the results at: https://sonarcloud.io/dashboard?id=eclipse-pmd_eclipse-pmd&branch=$GITHUB_REF_NAME" >> $GITHUB_STEP_SUMMARY
